# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KuroLive.KuroLive
PackageVersion: 0.32.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/aicodehub-vn/Ai-Code-Hub/releases/download/KuroLive-v0.32-rc/KuroLive_Setup.exe
  InstallerSha256: 4A82B0A93AF44FB6DC587078170B4FD52AF6D919D5963D605F25CAD78E44B7E9
ManifestType: installer
ManifestVersion: 1.12.0
